# Generated by Django 6.0.4 on 2026-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default_shipping', 'id']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.AddField(
            model_name='address',
            name='is_default_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
