# Generated by Django 6.0.4 on 2026-05-04 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agentprofile_customuser_assigned_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_agent', True), ('agent_profile__isnull', False), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
