# Generated by Django 6.0.4 on 2026-05-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_can_order',
            field=models.BooleanField(default=False, help_text='Buyer grants their assigned agent permission to place orders on their behalf.'),
        ),
        migrations.CreateModel(
            name='AgentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField()),
                ('utr_reference', models.CharField(blank=True, help_text='Bank UTR / transaction reference for this payout', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
    ]
