# Generated by Django 6.0.4 on 2026-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the buyer has paid / is expected to pay now', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance after advance payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_plan',
            field=models.CharField(blank=True, choices=[('advance', '10% Advance'), ('full', 'Full Payment (1% off)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Admin toggles this after confirming payment in bank'),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra 1% discount given for full UPI payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UPI Transaction Reference ID provided by buyer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('direct_upi', 'Direct UPI')], default='direct_upi', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
