# Generated by Django 6.0.4 on 2026-05-09 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_placed_by_agent_alter_commission_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof_type',
            field=models.CharField(choices=[('utr', 'UTR Number'), ('screenshot', 'Payment Screenshot'), ('none', 'No Proof (Manual Verification)')], default='none', help_text='What proof of payment the buyer submitted.', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of payment success screen uploaded by buyer', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Admin toggles this after confirming payment in bank'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_placed_on_behalf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UPI Transaction Reference ID provided by buyer', max_length=50, null=True),
        ),
    ]
