# Generated by Django 6.0.4 on 2026-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='mrp_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP per individual piece in the set', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='per_piece_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price per individual piece in the set', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='b2b_price',
            field=models.DecimalField(decimal_places=2, help_text='Set price (total wholesale price for the full set)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP for the full set', max_digits=10, null=True),
        ),
    ]
