# Generated by Django 6.0.4 on 2026-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariation_mrp_per_piece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption shown on the slide.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide without deleting it.')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='b2b_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='mrp_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='per_piece_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
