# Generated by Django 6.0.4 on 2026-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_heroslide_alter_color_hex_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='set_breakdown',
            field=models.CharField(blank=True, help_text='Size breakdown of the set, e.g. "1xL, 2xXL, 1x2XL, 1x3XL"', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
