# Generated by Django 6.0.4 on 2026-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariation_set_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(choices=[('XS', 'XS — Extra Small'), ('S', 'S — Small'), ('M', 'M — Medium'), ('L', 'L — Large'), ('XL', 'XL — Extra Large'), ('XXL', 'XXL — Double XL'), ('3XL', '3XL — Triple XL'), ('4XL', '4XL — Four XL'), ('5XL', '5XL — Five XL'), ('FS', 'FS — Free Size'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('L TO 3XL', 'L TO 3XL (Set)'), ('L TO 4XL', 'L TO 4XL (Set)'), ('L TO 5XL', 'L TO 5XL (Set)'), ('M TO 3XL', 'M TO 3XL (Set)'), ('M TO 4XL', 'M TO 4XL (Set)'), ('S TO XXL', 'S TO XXL (Set)')], max_length=20),
        ),
    ]
