# Generated by Django 6.0.4 on 2026-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariation_size_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(choices=[('XS', 'XS — Extra Small'), ('S', 'S — Small'), ('M', 'M — Medium'), ('L', 'L — Large'), ('XL', 'XL — Extra Large'), ('XXL', 'XXL — Double XL'), ('3XL', '3XL — Triple XL'), ('4XL', '4XL — Four XL'), ('5XL', '5XL — Five XL'), ('FS', 'FS — Free Size'), ('One Size', 'One Size'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('L TO 2XL', 'L TO 2XL (Set)'), ('L TO 3XL', 'L TO 3XL (Set)'), ('L TO 4XL', 'L TO 4XL (Set)'), ('L TO 5XL', 'L TO 5XL (Set)'), ('M TO 3XL', 'M TO 3XL (Set)'), ('M TO 4XL', 'M TO 4XL (Set)'), ('S TO XXL', 'S TO XXL (Set)'), ('4XL TO 5XL', '4XL TO 5XL (Set)'), ('28 TO 34', '28 TO 34 (Set)'), ('28 TO 36', '28 TO 36 (Set)'), ('30 TO 36', '30 TO 36 (Set)'), ('30 TO 38', '30 TO 38 (Set)'), ('32 TO 38', '32 TO 38 (Set)')], max_length=20),
        ),
    ]
