# Generated by Django 6.0.4 on 2026-05-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariation_size_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "L TO 3XL" or "M TO 4XL"', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sets are hidden from the variation dropdown.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order in the dropdown.')),
            ],
            options={
                'verbose_name': 'Size Set',
                'verbose_name_plural': 'Size Sets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='products.sizeset', verbose_name='Size'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'size_set', 'color')},
        ),
        migrations.CreateModel(
            name='SizeSetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Human-readable label shown in the dropdown, e.g. "1xL, 2xXL, 1xXXL, 1x3XL"', max_length=255)),
                ('breakdown_string', models.CharField(help_text='Exact string stored on the variation and shown to buyers in the tooltip. Usually the same as the label.', max_length=255)),
                ('size_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='products.sizeset')),
            ],
            options={
                'verbose_name': 'Size Set Breakdown',
                'verbose_name_plural': 'Size Set Breakdowns',
                'ordering': ['size_set__name', 'label'],
                'unique_together': {('size_set', 'breakdown_string')},
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size_breakdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='products.sizesetbreakdown', verbose_name='Set Breakdown'),
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='set_breakdown',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
    ]
